[profile.default]
src = "src"
out = "out"
solc_version="0.8.34"
libs = ["lib"]
fs_permissions=[{access="read-write",path="./"}]
remappings=['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
'@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/','murky/=lib/murky/']

[invariant]
runs=128
depth=128
fail_on_revert=true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options